name: Rancher Azure File Storage
description: |
  Docker volume plugin for Azure File Storage
version: 0.1.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
