.catalog:
    name: Network Services
    version: v0.1.3
    minimum_rancher_version: v1.5.4-rc1
    maximum_rancher_version: v1.5.99
    questions:
    - variable: DNS_RECURSER_TIMEOUT
      label: Timeout for Rancher DNS Recurser
      description: Specify timeout in seconds for DNS Recurser.
      required: true
      default: 2
      type: int
    - variable: TTL
      label: Default TTL for local responses
      description: Specify TTL in seconds for local responses.
      required: true
      default: 600
      type: int
